
# forward TFs

base_chassis_xyz:  '0.0 0.0 0.145'
base_chassis_rpy:  '0.0 0.0 0.0'

chassis_xsens_xyz: '0.0 0.0 0.09'
chassis_xsens_rpy: '0.0 0.0 0.0'

chassis_os1_xyz:   '0.0 0.0 0.2675'
chassis_os1_rpy:   '0.0 0.0 0.0'

chassis_d435i_xyz: '0.28 0.0 0.07'
chassis_d435i_rpy: '0.0 0.0 0.0'


# backward TFs

chassis_base_xyz:  '-0.0 -0.0 -0.145'
chassis_base_rpy:  '-0.0 -0.0 -0.0'

xsens_chassis_xyz: '-0.0 -0.0 -0.09'
xsens_chassis_rpy: '-0.0 -0.0 -0.0'

os1_chassis_xyz:   '-0.0 -0.0 -0.2675'
os1_chassis_rpy:   '-0.0 -0.0 -0.0'

d435i_chassis_xyz: '-0.28 -0.0 -0.07'
d435i_chassis_rpy: '-0.0 -0.0 -0.0'
